print('It\'s good')
print("Hello \"Rohan\"")
print("C:\\path\\to\\file")
print("Rohan is good boy \nRohan is best")
print("Rohan\tMishra")
print("Rohann\b")
print("\111")
print("\x48\x65")
print("\aRohan")
