import pandas as pd
df =pd.read_csv(r"C:\Users\C9IN\Downloads\Data\mtcars2.csv")
print(df)
print("\nIt show the rows and col\n")
print(df.shape)
print("It print all the information about data")
print(df.info())
print("It found min value from data ") 
print(df.min())
print()
print(df.max())
print()
print(df.head())
print()
print(df.head(10))
print()
print(df.tail())
print()
print(df.tail(4))
print()
print(df.count())
print()
print(df.mpg.mean())
print(df.mpg.median())
print(df.describe())

