marks = { "Harry": 23, "Rohan": 100,"Shubham": 56}
print("Data type is:", type(marks))
print("Marks of Rohan:", marks["Rohan"])
print("Complete Dictionary:", marks)
print("All items:", marks.items())
print("All keys:", marks.keys())
print("All values:", marks.values())
marks.update({"Harry": 40, "Renuka": 99})
print("Updated Dictionary:", marks)
print("Harry's Marks (safe access):", marks.get("Harry")) 
marks.pop("Harry")
print("After removing Harry:", marks)
print("Copy of marks:", marks.copy())
print("FromKeys Example:", dict.fromkeys(['Harry', 'Rohan'], 0))
print("Set Default Example:", marks.setdefault("d", 4))
print("Pop Last Item:", marks.popitem())
print("All Keys Truthy?", all(marks))
print("Any Key Truthy?", any(marks))
print("Length of Dictionary:", len(marks))
print("Sorted Keys:", sorted(marks))
print("Reversed Keys:", list(reversed(marks)))
try:
    print(marks["Ram"])
except:
    print("Ram's Marks (safe access):", marks.get("Ram"))   
marks.clear()
print("After clearing:", marks)